# Generated by Django 6.0 on 2026-01-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('link', models.TextField()),
                ('commit_count', models.IntegerField(default=0)),
                ('commit_month', models.JSONField(default=[0, 0, 0, 0, 0, 0])),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.TextField()),
                ('tech_stack', models.JSONField(default=dict)),
                ('commit_count', models.IntegerField(default=0)),
                ('commit_year', models.JSONField(default=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('link', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('forks_count', models.IntegerField()),
                ('stars', models.IntegerField()),
                ('tech_stack', models.JSONField(default={})),
                ('commit_count', models.IntegerField(default=0)),
                ('commit_month', models.JSONField(default=[0, 0, 0, 0, 0, 0])),
            ],
        ),
    ]
