# Generated by Django 6.0 on 2026-01-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_stat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='commit_month',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='developer',
            name='commit_year',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='developer',
            name='tech_stack',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='repository',
            name='commit_month',
            field=models.JSONField(),
        ),
    ]
