# Generated by Django 6.0 on 2026-01-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_stat_app', '0002_alter_contributor_commit_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repository',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
