# Generated by Django 6.0 on 2026-01-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_stat_app', '0003_developer_private_repository_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
