# Generated by Django 6.0 on 2026-01-19 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('git_stat_app', '0004_contributor_private'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='commit_month',
            new_name='commit_year',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='commit_month',
            new_name='commit_year',
        ),
    ]
